name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - run: npm run build
      - uses: biokah/crypto-dashboard@master
        with: 
          args: --acl public-read --follow-symlinks --delete
          env: 
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_S3_KEY_ID: ${{ secrets.AWS_S3_KEY_ID }}
            AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
            AWS_REGION: 'us-east-02'
            SOURCE_DIR: 'build'